import NextTopLoader from 'nextjs-toploader';
import '@/assets/css/style.css'
import '@/assets/css/dropdownmenu.css'
import '@/assets/css/sidebar.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import { Toaster } from 'react-hot-toast';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NextTopLoader
      color="#2299DD"
      height={2}
      speed={200}
       />
       <Toaster/>
        {children}
        </body>
    </html>
  );
}
